http:
  port: "8081"

users:
  api:
    host: "jsonplaceholder.typicode.com"
    port: "443"

db:
  host: "localhost"
  port: "5432"
  database: "hellomule_db"
  user: "hellomule_app"
  password: "![rAYl487kyCDa4MUnqHtGkA==]"
  sslmode: "disable"

api:
  id: "20964075"
